apiVersion: v1
kind: Service
metadata:
  name: emart-service
spec:
  selector:
    app: emart
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 32000
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32001
